// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZalbaService.Data.Context;

namespace ZalbaService.Migrations
{
    [DbContext(typeof(ZalbaDBContext))]
    partial class ZalbaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ZalbaService.Entities.Zalba", b =>
                {
                    b.Property<Guid>("ZalbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojOdluke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojResenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPodnosenjaZalbe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumResenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obrazlozenje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadnjaNaOsnovuZalbe")
                        .HasColumnType("int");

                    b.Property<string>("RazlogZalbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusZalbe")
                        .HasColumnType("int");

                    b.Property<int>("TipZalbe")
                        .HasColumnType("int");

                    b.HasKey("ZalbaID");

                    b.ToTable("Zalbe");
                });
#pragma warning restore 612, 618
        }
    }
}
