// <auto-generated />
using System;
using Licitacija1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Licitacija1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Licitacija1.Entities.DokumentModel", b =>
                {
                    b.Property<Guid>("dokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("licitacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("vrstaPodnosiocaDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.HasKey("dokumentID");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("Licitacija1.Entities.LicitacijaModel", b =>
                {
                    b.Property<Guid>("licitacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojLicitacije")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumLicitacije")
                        .HasColumnType("datetime2");

                    b.Property<int>("godina")
                        .HasColumnType("int");

                    b.Property<int>("korakCene")
                        .HasColumnType("int");

                    b.Property<int>("ogranicenjeLicitacije")
                        .HasColumnType("int");

                    b.Property<DateTime>("rokZaDostavuPrijava")
                        .HasColumnType("datetime2");

                    b.HasKey("licitacijaID");

                    b.ToTable("Licitacije");
                });
#pragma warning restore 612, 618
        }
    }
}
