// <auto-generated />
using System;
using KatastarskaOpstinaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KatastarskaOpstinaService.Migrations
{
    [DbContext(typeof(KatastarskaOpstinaDbContext))]
    [Migration("20230215120152_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KatastarskaOpstinaService.Models.KatastarskaOpstina", b =>
                {
                    b.Property<Guid>("KatastarskaOpstinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivOpstine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatutOpstineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KatastarskaOpstinaId");

                    b.HasIndex("StatutOpstineId");

                    b.ToTable("KatastarskeOpstine");
                });

            modelBuilder.Entity("KatastarskaOpstinaService.Models.StatutOpstine", b =>
                {
                    b.Property<Guid>("StatutOpstineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranjaStatuta")
                        .HasColumnType("datetime2");

                    b.Property<string>("SadrzajStatuta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatutOpstineId");

                    b.ToTable("StatutiOpstina");
                });

            modelBuilder.Entity("KatastarskaOpstinaService.Models.KatastarskaOpstina", b =>
                {
                    b.HasOne("KatastarskaOpstinaService.Models.StatutOpstine", "StatutOpstine")
                        .WithMany()
                        .HasForeignKey("StatutOpstineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
