// <auto-generated />
using System;
using Dokument.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dokument.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217135520_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dokument.Entities.DokumentEntity", b =>
                {
                    b.Property<int>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sablon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDokumenta")
                        .HasColumnType("int");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("Dokument.Entities.UgovorOZakupuEntity", b =>
                {
                    b.Property<Guid>("UgovorOZakupuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPotpisivanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("MestoPotpisivanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokDospeca")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokZaVracanje")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipGarancije")
                        .HasColumnType("int");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UgovorOZakupuID");

                    b.ToTable("Ugovori");
                });

            modelBuilder.Entity("Dokument.Entities.VerzijaDokumentaEntity", b =>
                {
                    b.Property<Guid>("VerzijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Revizija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verzija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerzijaID");

                    b.ToTable("VerzijeDokumenata");
                });
#pragma warning restore 612, 618
        }
    }
}
